# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 公有的 Specs 地址
source 'https://github.com/CocoaPods/Specs.git'
# 私有的 Specs 地址
source 'https://github.com/GitHubZHH/HGSpecs.git'

target 'HGPGY' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'HGCategorys_Private'
  pod 'HGBaseClass'

end
